name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Run Format Check
      run: cargo fmt --all -- --check

    - name: Run Clippy
      run: cargo clippy -- -D warnings

    - name: Run Tests
      run: cargo test --verbose